package it.italiaonline.rnd.url

import spock.lang.Specification

/**
 * This Spock specification was auto generated by 'gigawatt'
 * @author gsus
 * @date 19-02-2017 10.27
 */
class QParamsFilterSpec extends Specification {
	def "someQParamsFilterMethod returns true"() {
		setup:
			QParamsFilter lib = new QParamsFilter()
		when:
			Boolean result = lib.someQParamsFilterMethod()
		then:
			result == true
	}
}
