package it.italiaonline.rnd.url

import groovy.util.logging.Slf4j

/**
 * This Groovy source file was auto generated by 'gigawatt'
 * @author gsus
 * @date 19-02-2017 10.27
 */
@Slf4j
class QParamsFilter {
	/**
	 * This method returns always true.
	 */
	Boolean someQParamsFilterMethod() {
		true
	}
}
